version: '3'

services:
 backend_sgav:
    restart: always
    command: python3 main.py
    build:
      context: ./sgav_backend
    ports:
      - "8080:8080"
    env_file:
      - ./sgav_backend/.env
    depends_on:
      - mongodb_container
    environment:
      MONGODB_HOST: mongodb_container
      MONGODB_PORT: 27017
      MONGODB_USER: root
      MONGODB_PASSWORD: root
    volumes:
      - shared-bots:/app/bots
    networks:
      - mynetwork
 sgav:
    restart: always
    build:
      context: ./sgav
    depends_on:
      - backend_sgav
    env_file:
      - ./sgav/.env    
    ports:
      - "3000:80"
    networks:
      - mynetwork

 mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

 test_bots:
      restart: always
      build:
        context: ./test-bots-api
      ports:
        - "8085:8085"
      depends_on:
        - backend_sgav
      volumes:
        - shared-bots:/app/bots
      networks:
        - mynetwork

volumes:
 mongodb_data_container:
 shared-bots:

networks:
  mynetwork: