version: '3'
services:
 backend:
    build: ./sgav_backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb_container
    environment:
      MONGODB_HOST: mongodb_container
      MONGODB_PORT: 27017
      MONGODB_USER: root
      MONGODB_PASSWORD: root
      
 frontend:
    build: ./sgav
    ports:
      - "3000:3000"

 mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
 mongodb_data_container:
